// resources/js/Pages/PrivacyPolicy.tsx
import { Head } from '@inertiajs/react';

export default function PrivacyPolicy({ policy }: { policy: string }) {
  return (
		<>
			<Head title="Privacy Policy"/>

			<div className="bg-dots-darker bg-slate-900 font-sans text-slate-100 antialiased">
				<div>
					<div className="flex min-h-screen flex-col items-center py-6 sm:pt-0">
						{/* logo */}

						<div
							dangerouslySetInnerHTML={{ __html: policy }}
							className="prose prose-invert mx-auto mt-6 w-full overflow-hidden bg-slate-800 p-6 shadow-md sm:max-w-5xl sm:rounded-2xl"
						/>
					</div>
				</div>
			</div>
		</>
  );
}

// resources/js/Pages/PrivacyPolicy.vue
<template>
    <Head title="Privacy Policy" />

    <div class="font-sans text-gray-900 antialiased">
        <div class="pt-4 bg-gray-100">
            <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
                <div>
                    <jet-authentication-card-logo />
                </div>

                <div v-html="policy" class="w-full sm:max-w-5xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { Head } from '@inertiajs/vue3';
import JetAuthenticationCardLogo from '@/Jetstream/AuthenticationCardLogo.vue'

export default {
    props: ['policy'],

    components: {
        Head,
        JetAuthenticationCardLogo,
    },
}
</script>
