// resources/js/Pages/Verify.tsx
import { Head, useForm } from '@inertiajs/react';
import Authenticated from '@/Layouts/AuthenticatedLayout';
import InputLabel from '@/Components/InputLabel';
import TextInput from '@/Components/TextInput';
import InputError from '@/Components/InputError';
import { PrimaryButton } from '@/Components/Buttons';
import { PageProps } from '@/types';
import { FormEventHandler } from 'react';

export default function VerifyClaim({ auth }: PageProps) {
  const {
    data, setData, put, processing, errors,
  } = useForm({
    verification_code: '',
  });

  const submit: FormEventHandler = (e) => {
    e.preventDefault();

    put(route('claims.verify'));
  };

  return (
    <Authenticated
      user={auth.user}
    >
      <Head title="Verify your claim" />

      <div className="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
        <div className="sm:mx-auto sm:w-full sm:max-w-md">
          <h2 className="mt-6 text-center text-2xl font-extrabold text-gray-900">
            Verify your claim
          </h2>
        </div>

        <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
          <div className="bg-slate-800 px-4 py-8 shadow sm:rounded-lg sm:px-10">
            <form onSubmit={submit} className="space-y-6">
              <div>
                <InputLabel htmlFor="code" value="Verification code" />

                <TextInput
                  id="code"
                  type="text"
                  className="mt-1 block w-full"
                  value={data.verification_code}
                  onChange={(e) => setData('verification_code', e.target.value)}
                  required
                  autoFocus
                />

                <InputError message={errors.verification_code || errors.message} className="mt-2" />
              </div>

              <PrimaryButton className="flex w-full justify-center" disabled={processing}>
                Verify
              </PrimaryButton>
            </form>
          </div>
        </div>
      </div>
    </Authenticated>
  );
}

// resources/js/Pages/Verify.vue
<template>
    <app-layout title="Verify your claim">
        <div class="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
            <div class="sm:mx-auto sm:w-full sm:max-w-md">
                <h2 class="mt-6 text-center text-2xl font-extrabold text-gray-900">Verify your claim</h2>
            </div>

            <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
                <div class="bg-slate-800 px-4 py-8 shadow sm:rounded-lg sm:px-10">
                    <form class="space-y-6" action="#" method="POST">
                        <div>
                            <InputLabel for="verification_code" value="Verification code" />

                            <TextInput
                                id="verification_code"
                                type="text"
                                class="mt-1 block w-full"
                                v-model="form.verification_code"
                                required
                                autofocus
                            />

                            <InputError class="mt-2" :message="form.errors?.message" />
                        </div>

                        <div>
                            <PrimaryButton type="submit" @click.prevent="verify" class="flex w-full justify-center">Verify</PrimaryButton>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </app-layout>
</template>

<script>
import AppLayout from '@/Layouts/AppLayout.vue';
import InputLabel from '@/Components/InputLabel.vue';
import InputError from '@/Components/InputError.vue';
import TextInput from '@/Components/TextInput.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';

export default {
  components: {
    AppLayout,
    InputLabel,
    InputError,
    TextInput,
    PrimaryButton,
  },
  data() {
    return {
      form: this.$inertia.form({
        _method: 'patch',
        verification_code: '',
      }),
    };
  },
  methods: {
    verify() {
      this.form.post(route('claims.verify.update'), {
        errorBag: 'updateClaim',
      });
    },
  },
};
</script>
