// resources/js/Components/Stars.tsx
import { StarIcon } from '@heroicons/react/24/solid';

type StarsProps = {
  score: string;
  className?: string;
}

export default function Stars({ className = '', score }: StarsProps) {
  return [...Array(5)].map((n, index) => (
    <StarIcon key={index} className={
      `fill-current ${n <= score ? 'text-sky-500' : 'text-sky-300'} ${className}`
    } />
  ));
}

// resources/js/Components/Stars.vue
<template>
    <template v-for="n in 5" :key="n">
        <StarIcon :class="[size, n <= score ? 'text-sky-500' : 'text-gray-300', 'fill-current']" />
    </template>
</template>

<script>
    import { StarIcon } from '@heroicons/vue/24/solid';
    
    export default {
        props: ['size', 'score'],
        components: {
            StarIcon,
        }
    }
</script>
