// resources/js/Pages/Admin/Housing/Edit.vue
<template>
    <admin-layout>
        <div class="max-w-5xl mx-auto bg-white overflow-hidden shadow rounded-lg">
            <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
                <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                    <div class="ml-4 mt-2">
                        <h3 class="text-2xl leading-6 font-medium text-gray-900">Edit Housing</h3>
                    </div>
                    <div class="ml-4 mt-2 flex-shrink-0 space-x-2">
                        <!-- <Link :href="route('housing.show', [housing.slug])" class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">Back to profile</Link> -->
                        <button @click.prevent="updateHousingInformation" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">Save changes</button>
                    </div>
                </div>
            </div>
            <div class="px-4 py-5 sm:p-6">
                <div class="md:grid md:grid-cols-3 md:gap-6">
                    <div class="md:col-span-1">
                        <div class="px-4 sm:px-0">
                            <h3 class="text-lg font-medium leading-6 text-gray-900">Housing Information</h3>
                            <p class="mt-1 text-sm text-gray-600">
                                Use a permanent address where you can receive mail.
                            </p>
                        </div>
                    </div>
                    <div class="mt-5 md:mt-0 md:col-span-2">
                        <form>
                            <div class="px-4 py-1 sm:px-6">
                                <div class="grid grid-cols-6 gap-6">
                                    <div class="col-span-6">
                                        <label for="housing-name" class="block text-sm font-medium text-gray-700">Housing name</label>
                                        <input type="text" v-model="housing.name" name="housing-name" id="housing-name" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6">
                                        <label for="housing-website" class="block text-sm font-medium text-gray-700">
                                            Website
                                        </label>
                                        <div class="mt-1 flex rounded-md shadow-sm">
                                            <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                                https://
                                            </span>
                                            <input type="text" name="housing-website" id="housing-website" class="focus:ring-sky-500 focus:border-sky-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300" placeholder="www.example.com" v-model="housing.website_url" />
                                        </div>
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="email-address" class="block text-sm font-medium text-gray-700">Email address</label>
                                        <input type="text" v-model="housing.email_address" name="email-address" id="email-address" autocomplete="email" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                        <!-- <jet-input-error :message="housing?.errors.email_address" class="mt-1" /> -->
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="phone-number" class="block text-sm font-medium text-gray-700">Phone number</label>
                                        <input type="text" v-model="housing.phone_number" name="phone-number" id="phone-number" placeholder="(555) 555-5555" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                        <!-- <jet-input-error :message="housing?.errors.phone_number" class="mt-1" /> -->
                                    </div>

                                    <div class="col-span-6">
                                        <label for="street-address" class="block text-sm font-medium text-gray-700">Street address</label>
                                        <input type="text" v-model="housing.street" name="street-address" id="street-address" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6 sm:col-span-6 lg:col-span-3">
                                        <label for="city" class="block text-sm font-medium text-gray-700">City</label>
                                        <input type="text" v-model="housing.city" name="city" id="city" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                        <label for="postal-code" class="block text-sm font-medium text-gray-700">ZIP / Postal</label>
                                        <input type="text" v-model="housing.postal_code" name="postal-code" id="postal-code" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                        <label for="rent" class="block text-sm font-medium text-gray-700">Rent range</label>
                                        <input type="text" v-model="housing.rent_range" name="rent" id="rent" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                        <label for="bedrooms" class="block text-sm font-medium text-gray-700">Bedroom range</label>
                                        <input type="text" v-model="housing.bedroom_range" name="bedrooms" id="bedrooms" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                        <label for="bathrooms" class="block text-sm font-medium text-gray-700">Bathroom range</label>
                                        <input type="text" v-model="housing.bathroom_range" name="bathrooms" id="bathrooms" class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" />
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <Listbox as="div" v-model="selected">
                                            <ListboxLabel class="block text-sm font-medium text-gray-700">
                                                Housing type
                                            </ListboxLabel>
                                            <div class="mt-1 relative">
                                                <ListboxButton class="bg-white relative w-full border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-sky-500 focus:border-sky-500 sm:text-sm">
                                                    <span class="block truncate">{{ selected.name }}</span>
                                                    <span class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                                                        <ChevronUpDownIcon class="h-5 w-5 text-gray-400" aria-hidden="true" />
                                                    </span>
                                                </ListboxButton>

                                                <transition leave-active-class="transition ease-in duration-100" leave-from-class="opacity-100" leave-to-class="opacity-0">
                                                    <ListboxOptions class="absolute z-10 mt-1 w-full bg-white shadow-lg max-h-60 rounded-md py-1 text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm">
                                                        <ListboxOption as="template" v-for="(type, typeIdx) in housingTypes" :key="typeIdx" :value="type" v-slot="{ active, selected }">
                                                            <li @click="updateHousingType(type.value)" :class="[active ? 'text-white bg-sky-600' : 'text-gray-900', 'cursor-default select-none relative py-2 pl-3 pr-9']">
                                                                <span :class="[selected ? 'font-semibold' : 'font-normal', 'block truncate']">
                                                                    {{ type.name }}
                                                                </span>

                                                                <span v-if="selected" :class="[active ? 'text-white' : 'text-sky-600', 'absolute inset-y-0 right-0 flex items-center pr-4']">
                                                                    <CheckIcon class="h-5 w-5" aria-hidden="true" />
                                                                </span>
                                                            </li>
                                                        </ListboxOption>
                                                    </ListboxOptions>
                                                </transition>
                                            </div>
                                        </Listbox>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="px-4 py-4 sm:px-6">
                <div class="flex justify-end">
                    <button @click.prevent="updateHousingInformation" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">Save changes</button>
                </div>
            </div>
        </div>
    </admin-layout>
</template>

<script setup>
    import AdminLayout from '@/Layouts/AdminLayout.vue';
    import { Listbox, ListboxButton, ListboxLabel, ListboxOption, ListboxOptions } from '@headlessui/vue';
    import { CheckIcon, ChevronUpDownIcon } from '@heroicons/vue/24/solid';
    import { ref } from 'vue';
    import { housingTypes } from '@/Utils/housingTypes';
    import { router } from '@inertiajs/vue3';

    const props = defineProps({
        housing: Object,
    });

    const selected = ref(housingTypes[
        housingTypes.findIndex(type => type.value === props.housing.housing_type)
    ]);

    const updateHousingType = (value) => {
        props.housing.housing_type = value;
    }

    const updateHousingInformation = () =>  {
        router.post(route('admin.housing.update', [props.housing.id]), props.housing, {
            errorBag: 'updateHousingInformation',
            preserveScroll: true,
        });
    }
</script>

// resources/js/Pages/StudentHousing/Edit.tsx
import { Fragment } from 'react';
import { Head, useForm } from '@inertiajs/react';
import { Listbox, Transition } from '@headlessui/react';
import { CheckIcon, ChevronDownIcon } from '@heroicons/react/24/solid';
import Authenticated from '@/Layouts/AuthenticatedLayout';
import { PrimaryButton, SecondaryButton } from '@/Components/Buttons';
import InputLabel from '@/Components/InputLabel';
import TextArea from '@/Components/TextArea';
import InputError from '@/Components/InputError';
import TextInput from '@/Components/TextInput';
import TextInputWithAddon from '@/Components/TextInputWithAddon';
import classNames from '@/Utils/classNames';
import Checkbox from '@/Components/Checkbox';
import capitalize from '@/Utils/strings';
import UpdateProfileImage from '@/Components/UpdateProfileImage';
import UpdateCoverImage from '@/Components/UpdateCoverImage';
import { Amenity, Housing, PageProps } from '@/types';

const housingTypes = [
  { name: 'Single', value: 'single' },
  { name: 'Married', value: 'married' },
];

export default function StudentHousingEdit({ availableAmenities, auth, housing }: PageProps & { availableAmenities: Amenity[], housing: Housing }) {
  const {
    data, setData, errors, put, reset, processing,
  } = useForm({
    ...housing,
    cover: {},
    profile: {},
  });

  const updateProfile = (value: File) => {
    let { profile } = data;
    profile = value;
    setData('profile', profile);
  };

  const updateCover = (value: File) => {
    let { cover } = data;
    cover = value;
    setData('cover', cover);
  };

  const findAmenity = (selectedAmenity: Amenity) => (data.amenities.indexOf(selectedAmenity) !== -1);

  const updateAmenities = (selectedAmenity: Amenity) => {
    const index = data.amenities.indexOf(selectedAmenity);
    const { amenities } = data;

    if (index < 0) {
      amenities.push(selectedAmenity);
      setData({ ...data, amenities });
    } else {
      amenities.splice(index, 1);
      setData({ ...data, amenities });
    }
  };

  const submit = () => {
    put(route('housing.update'), {
      preserveScroll: true,
      onSuccess: () => reset(),
    });
  };

  return (
    <Authenticated
      user={auth.user}
    >
      <Head title={`Edit ${housing.name}`} />

      <div className="mx-auto max-w-7xl py-10 sm:px-6 lg:px-8">
        <div className="divide-y divide-slate-600 overflow-hidden rounded-lg bg-slate-800 shadow-lg">
          <div className="px-4 py-5 sm:px-6">
            <div className="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
              <div className="ml-4 mt-2">
                <h2 className="text-2xl font-medium leading-6 text-slate-200">
                  Edit {housing.name}
                </h2>
              </div>
              <div className="ml-4 mt-2 shrink-0 space-x-2">
                <SecondaryButton href={route('housing.show', [housing.slug])}>
                  Back to profile
                </SecondaryButton>
                <PrimaryButton type="button" onClick={submit} disabled={processing}>
                  Save changes
                </PrimaryButton>
              </div>
            </div>
          </div>
          <form encType="multipart/form-data">
            <div className="divide-y divide-slate-600">
              <div className="p-4 sm:p-6 lg:px-8">
                <div className="md:grid md:grid-cols-3 md:gap-6">
                  <div className="md:col-span-1">
                    <div className="px-4 sm:px-0">
                      <h3 className="text-lg font-medium leading-6 text-slate-200">
                        Profile
                      </h3>
                      <p className="mt-1 text-sm text-slate-400">
                        This information will be displayed publicly so be careful what you share.
                      </p>
                    </div>
                  </div>
                  <div className="mt-5 md:col-span-2 md:mt-0">
                    <div>
                      <div className="space-y-6 px-4 py-1 sm:px-6">
                        <div>
                          <InputLabel htmlFor="about" value="About" />

                          <TextArea
                            value={data.about || ''}
                            onChange={(e) => setData('about', e.target.value)}
                            className="mt-1 block w-full"
                          />

                          <div className="mt-2 flex items-center justify-between text-sm text-slate-400">
                            <p>
                              Bried description of your property.
                            </p>
                            <p>
                              1,000 character limit
                            </p>
                          </div>

                          <InputError message={errors.about} className="mt-1" />
                        </div>

                        <UpdateProfileImage
                          name={housing.name}
                          imageUrl={housing.profile_image_url}
                          imagePath={housing.profile_image_path}
                          onChange={(value) => updateProfile(value)}
                          error={errors.profile}
                        />

                        <UpdateCoverImage
                          name={housing.name}
                          imageUrl={housing.cover_image_url}
                          imagePath={housing.cover_image_path}
                          onChange={(value) => updateCover(value)}
                          error={errors.cover}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-4 sm:p-6 lg:px-8">
                <div className="md:grid md:grid-cols-3 md:gap-6">
                  <div className="md:col-span-1">
                    <div className="px-4 sm:px-0">
                      <h3 className="text-lg font-medium leading-6 text-slate-200">
                        Housing Information
                      </h3>
                      <p className="mt-1 text-sm text-slate-400">
                        Use a permanent address where you can receive mail.
                      </p>
                    </div>
                  </div>
                  <div className="mt-5 md:col-span-2 md:mt-0">
                    <div>
                      <div className="px-4 py-1 sm:px-6">
                        <div className="grid grid-cols-6 gap-6">
                          <div className="col-span-6 sm:col-span-4">
                            <InputLabel htmlFor="name" value="Housing name" />

                            <TextInput
                              id="name"
                              name="name"
                              className="mt-1 block w-full"
                              value={data.name || ''}
                              onChange={(e) => setData('name', e.target.value)}
                            />

                            <InputError message={errors.name} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-4">
                            <InputLabel htmlFor="website" value="Website" />

                            <TextInputWithAddon
                              id="website"
                              name="website"
                              value={data.website_url || ''}
                              onChange={(e) => setData('website_url', e.target.value)}
                              placeholder="www.example.com"
                              addonText="https://"
                            />

                            <InputError message={errors.website_url} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3">
                            <InputLabel htmlFor="email" value="Email address" />

                            <TextInput
                              id="email"
                              type="email"
                              name="email"
                              className="mt-1 block w-full"
                              value={data.email_address || ''}
                              onChange={(e) => setData('email_address', e.target.value)}
                            />

                            <InputError message={errors.email_address} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3">
                            <InputLabel htmlFor="phone" value="Phone number" />

                            <TextInput
                              id="phone"
                              name="phone"
                              className="mt-1 block w-full"
                              value={data.phone_number || ''}
                              onChange={(e) => setData('phone_number', e.target.value)}
                            />

                            <InputError message={errors.phone_number} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-4">
                            <InputLabel htmlFor="street" value="Street address" />

                            <TextInput
                              id="street"
                              name="street"
                              className="mt-1 block w-full"
                              value={data.street || ''}
                              onChange={(e) => setData('street', e.target.value)}
                            />

                            <InputError message={errors.street} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3">
                            <InputLabel htmlFor="city" value="City" />

                            <TextInput
                              id="city"
                              name="city"
                              className="mt-1 block w-full"
                              value={data.city || ''}
                              onChange={(e) => setData('city', e.target.value)}
                            />

                            <InputError message={errors.city} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                            <InputLabel htmlFor="postal_code" value="ZIP / Postal code" />

                            <TextInput
                              id="postal_code"
                              name="postal_code"
                              className="mt-1 block w-full"
                              value={data.postal_code || ''}
                              onChange={(e) => setData('postal_code', e.target.value)}
                            />

                            <InputError message={errors.postal_code} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                            <InputLabel htmlFor="rent" value="Rent range" />

                            <TextInput
                              id="rent"
                              name="rent"
                              className="mt-1 block w-full"
                              value={data.rent_range || ''}
                              onChange={(e) => setData('rent_range', e.target.value)}
                            />

                            <InputError message={errors.rent_range} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                            <InputLabel htmlFor="bedroom" value="Bedroom range" />

                            <TextInput
                              id="bedroom"
                              name="bedroom"
                              className="mt-1 block w-full"
                              value={data.bedroom_range || ''}
                              onChange={(e) => setData('bedroom_range', e.target.value)}
                            />

                            <InputError message={errors.bedroom_range} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                            <InputLabel htmlFor="bathroom" value="Bathroom range" />

                            <TextInput
                              id="bathroom"
                              name="bathroom"
                              className="mt-1 block w-full"
                              value={data.bathroom_range || ''}
                              onChange={(e) => setData('bathroom_range', e.target.value)}
                            />

                            <InputError message={errors.bathroom_range} className="mt-1" />
                          </div>

                          <div className="col-span-6 sm:col-span-3">
                            <Listbox value={data.housing_type} onChange={(value) => setData('housing_type', value)}>
                              {({ open }) => (
                                <>
                                  <Listbox.Label className="block text-sm font-medium text-slate-300">
                                    Housing type
                                  </Listbox.Label>
                                  <div className="relative mt-1">
                                    <Listbox.Button className="relative w-full cursor-default rounded-md border border-slate-700 bg-slate-900 py-2 pl-3 pr-10 text-left text-slate-300 shadow-sm focus:border-slate-500 focus:outline-none focus:ring-1 focus:ring-slate-500">
                                      <span className="block truncate">
                                        {capitalize(data.housing_type)}
                                      </span>
                                      <span className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
                                        <ChevronDownIcon className="h-5 w-5 text-slate-400" aria-hidden="true" />
                                      </span>
                                    </Listbox.Button>

                                    <Transition
                                      show={open}
                                      as={Fragment}
                                      leave="transition ease-in duration-100"
                                      leaveFrom="opacity-100"
                                      leaveTo="opacity-0"
                                    >
                                      <Listbox.Options className="absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-slate-900 py-1 text-base shadow-lg ring-1 ring-black/5 focus:outline-none">
                                        {housingTypes.map((type, index) => (
                                          <Listbox.Option
                                            key={index}
                                            value={type.value}
                                            className={({ active }) => classNames(active ? 'bg-sky-600 text-white' : 'text-slate-200', 'relative cursor-default select-none py-2 pl-3 pr-9')}
                                          >
                                            {({ selected, active }) => (
                                              <>
                                                <span className={classNames(selected ? 'font-semibold' : 'font-normal', 'block truncate')}>
                                                  {type.name}
                                                </span>

                                                {selected ? (
                                                  <span
                                                    className={classNames(
                                                      active ? 'text-white' : 'text-sky-600',
                                                      'absolute inset-y-0 right-0 flex items-center pr-4',
                                                    )}
                                                  >
                                                    <CheckIcon className="h-5 w-5" aria-hidden="true" />
                                                  </span>
                                                ) : null}
                                              </>
                                            )}
                                          </Listbox.Option>
                                        ))}
                                      </Listbox.Options>
                                    </Transition>
                                  </div>
                                </>
                              )}
                            </Listbox>
                          </div>

                          {data.housing_type === 'single' ? (
                            <div className="col-span-6 sm:col-span-4">
                              <label className="flex items-center">
                                <Checkbox
                                  id="byui_approved"
                                  name="byui_approved"
                                  checked={data.byui_approved || false}
                                  onChange={(e) => setData('byui_approved', e.target.checked)}
                                />
                                <span className="ml-2 text-slate-400">
                                  BYU-Idaho Approved
                                </span>
                              </label>
                              <p className="mt-2 text-sm text-slate-400">
                                By checking this box, you certify that this property is BYU-Idaho approved single student housing.
                              </p>
                            </div>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-4 sm:p-6 lg:px-8">
                <div className="md:grid md:grid-cols-3 md:gap-6">
                  <div className="md:col-span-1">
                    <div className="px-4 sm:px-0">
                      <h3 className="text-lg font-medium leading-6 text-slate-200">
                        Amenities
                      </h3>
                      <p className="mt-1 text-sm text-slate-400">
                        Select the amenities available at this property.
                      </p>
                    </div>
                  </div>
                  <div className="mt-5 md:col-span-2 md:mt-0">
                    <div>
                      <div className="px-4 py-1 sm:px-6">
                        <div className="grid grid-cols-6 gap-6">
                          {availableAmenities.map((amenity) => (
                            <div key={amenity.id} className="col-span-6 sm:col-span-2">
                              <label className="flex items-center">
                                <Checkbox
                                  checked={findAmenity(amenity)}
                                  onChange={() => updateAmenities(amenity)}
                                />
                                <span className="ml-3 text-slate-400">
                                  {amenity.name}
                                </span>
                              </label>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="p-4 sm:p-6">
                <div className="flex justify-end">
                  <PrimaryButton type="button" onClick={submit} disabled={processing}>
                    Save changes
                  </PrimaryButton>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </Authenticated>
  );
}
