// resources/js/Pages/Errors/404.tsx
import { type ReactElement } from 'react'
import { Head, Link } from '@inertiajs/react'
import MainNav from '@/Components/MainNav'
import { type PageProps } from '@/types'

export default function Error404 ({ auth }: PageProps): ReactElement {
  return <>
    <Head title="Page not found"/>

    <MainNav user={auth.user}/>

    <main className="py-20">
      <div className="flex min-h-full flex-col pb-12 pt-32">
        <div className="mx-auto flex w-full max-w-7xl grow flex-col justify-center px-4 sm:px-6 lg:px-8">
          <div className="py-16">
            <div className="text-center">
              <p className="text-sm font-semibold uppercase tracking-wide text-sky-600">
                404 error
              </p>
              <h1 className="mt-2 text-4xl font-extrabold tracking-tight text-slate-800 dark:text-slate-100 sm:text-5xl">
                Page not found.
              </h1>
              <p className="mt-2 text-base text-slate-500">
                Sorry, we couldn&apos;t find the page you&apos;re looking for.
              </p>
              <div className="mt-6 flex flex-col space-y-4">
                <Link href={route('housing.single')}
                  className="text-base font-medium text-sky-600 hover:text-sky-700"
                >
                  Go to single housing listings <span aria-hidden="true"> &rarr;</span>
                </Link>
                <Link href={route('housing.married')}
                  className="text-base font-medium text-sky-600 hover:text-sky-700"
                >
                  Go to married housing listings <span aria-hidden="true"> &rarr;</span>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </>
}

// resources/js/Pages/Errors/404.vue
<template>
    <app-layout title="404">
        <div class="min-h-full pt-32 pb-12 flex flex-col">
            <main class="flex-grow flex flex-col justify-center max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8">
                <div class="py-16">
                    <div class="text-center">
                        <p class="text-sm font-semibold text-sky-600 uppercase tracking-wide">404 error</p>
                        <h1 class="mt-2 text-4xl font-extrabold text-gray-900 tracking-tight sm:text-5xl">Page not found.</h1>
                        <p class="mt-2 text-base text-gray-500">Sorry, we couldn’t find the page you’re looking for.</p>
                        <div class="mt-6 flex flex-col space-y-4">
                            <Link :href="route('housing.single')" class="text-base font-medium text-sky-600 hover:text-sky-700">Go to single housing listings<span aria-hidden="true"> &rarr;</span></Link>
                            <Link :href="route('housing.married')" class="text-base font-medium text-sky-600 hover:text-sky-700">Go to married housing listings<span aria-hidden="true"> &rarr;</span></Link>
                        </div>
                    </div>
                </div>
            </main>
            <footer class="flex-shrink-0 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8">
                <nav class="flex justify-center space-x-4">
                    <a href="#" class="text-sm font-medium text-gray-500 hover:text-gray-600">Contact Support</a>
                </nav>
            </footer>
        </div>
    </app-layout>
</template>

<script>
    import { Link } from '@inertiajs/vue3';
    import AppLayout from '@/Layouts/AppLayout.vue';
    import ApplicationMark from '@/Components/ApplicationMarkBlue.vue';

    export default {
        components: {
            AppLayout,
            ApplicationMark,
            Link,
        },
    }
</script>
