// resources/js/Pages/Admin/Housing.vue
<template>
    <app-layout title="Admin Housing">
        <div class="py-12 px-4 md:px-0">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <h2>Housing</h2>
                <div class="py-4 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
                    <button type="button" class="relative block w-full border-2 border-gray-300 border-dashed rounded-lg p-12 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <span class="mt-2 block text-sm font-medium text-gray-900">
                            Create housing
                        </span>
                    </button>
                    <Link href="#">
                        <div class="relative shadow-xl rounded-xl overflow-hidden min-h-full group">
                            <div class="absolute inset-0">
                                <img src="https://images.unsplash.com/photo-1460317442991-0ec209397118?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&h=1200&q=80" alt="" class="h-full w-full object-cover transform transition duration-200 ease-in-out group-hover:scale-110">
                                <div class="absolute inset-0 bg-gradient-to-r from-sky-300 to-blue-300" :style="{ mixBlendMode: 'multiply' }"></div>
                            </div>
                            <div class="relative flex flex-col min-h-full px-4 pt-20 pb-4">
                                <div class="flex-grow">
                                    <p class="font-bold text-white text-lg truncate">Greenleaf Apartments</p>
                                </div>
                            </div>
                        </div>
                    </Link>
                </div>
            </div>
        </div>
    </app-layout>
</template>

<script>
    import AppLayout from '@/Layouts/AppLayout';
    import { Link } from '@inertiajs/inertia-vue3';

    export default {
        components: {
            AppLayout,
            Link,
        },
    }
</script>

// resources/js/Pages/Admin/Housing/Index.tsx
import { Head, Link } from '@inertiajs/react';
import Admin from '@/Layouts/AdminLayout';
import { Housing, PageProps } from '@/types';

export default function HousingIndex({ auth, housings }: PageProps & { housings: Housing[] }) {
  return (
    <Admin
      user={auth.user}
    >
      <Head title="Admin Housing" />

      <div className="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="sm:flex sm:items-center">
          <div className="sm:flex-auto">
            <h1 className="text-base font-semibold leading-6 text-gray-900">
              Student Housing
            </h1>
            <p className="mt-2 text-sm text-gray-700">
              A list of all student housing including their name and type.
            </p>
          </div>
          <div className="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
            <Link
              href={route('admin.housing.create')}
              className="block rounded-md bg-sky-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-sky-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600"
            >
              Add housing
            </Link>
          </div>
        </div>
        <div className="mt-8 flow-root">
          <div className="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div className="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
              <div className="overflow-hidden ring-1 ring-black/5 sm:rounded-lg">
                <table className="min-w-full divide-y divide-gray-300">
                  <thead className="bg-gray-50">
                    <tr>
                      <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                        Name
                      </th>
                      <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                        Housing Type
                      </th>
                      <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                        # of Reviews
                      </th>
                      <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                        <span className="sr-only">Edit</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200 bg-white">
                    {housings.map((housing) => (
                      <tr key={housing.id}>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                          {housing.name}
                        </td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{housing.housing_type}</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{housing.reviews_count}</td>
                        <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                          <Link href={route('admin.housing.show', [housing.id])} className="text-sky-600 hover:text-sky-900">
                            Edit<span className="sr-only">, {housing.name}</span>
                          </Link>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Admin>
  );
}
