// resources/js/Layouts/GuestLayout.tsx
import { PropsWithChildren } from 'react';
import { Link } from '@inertiajs/react';
import ApplicationLogo from '@/Components/ApplicationLogo';

export default function Guest({ children }: PropsWithChildren) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-slate-900 bg-dots-lighter pt-6 selection:bg-sky-500 selection:text-white sm:justify-center sm:pt-0">
      <div>
        <Link href="/">
          <ApplicationLogo className="h-10 w-auto fill-current text-slate-500 md:h-16" />
        </Link>
      </div>

      <div className="mt-6 w-full overflow-hidden bg-slate-800 px-6 py-4 shadow-md sm:max-w-md sm:rounded-lg">
        {children}
      </div>
    </div>
  );
}

// resources/js/Layouts/GuestLayout.vue
<script setup>
import ApplicationLogo from '@/Components/ApplicationLogo.vue';
import { Link } from '@inertiajs/vue3';
</script>

<template>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-slate-100 dark:bg-dots-lighter dark:bg-slate-900 selection:bg-sky-500 selection:text-white">
        <div>
            <Link href="/">
                <ApplicationLogo class="w-auto h-16 fill-current text-slate-500" />
            </Link>
        </div>

        <div
            class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white dark:bg-slate-800 shadow-md overflow-hidden sm:rounded-lg"
        >
            <slot />
        </div>
    </div>
</template>
